name: shengsheng-CI

on:
  pull_request_target:
    branches: [ main ]
    types: [opened,synchronize, labeled ,unlabeled]

jobs:
  check-ci-approve:
    name: ci-approve
    runs-on: ubuntu-latest
    steps:
      - name: Check for ci-approve label
        uses: actions/github-script@v7
        with:
          script: |
            const labels = context.payload.pull_request.labels.map(label => label.name);
            if (!labels.includes('ci-approve')) {
              core.setFailed('请等待 ci-approve 标签');
            }

  run-tests:
    needs: check-ci-approve 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17' 
          distribution: 'temurin' 
      - name: Run Maven Tests
        run: mvn test
